<?php

namespace Acme\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findOneByIdJoinedToCategory($id) {

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT p, c FROM AcmeDemoBundle:Product p
                 JOIN p.category c
                 WHERE p.id = :id'
            )->setParameter('id',$id);
        try {
            return $query->getScalarResult();
        } catch(\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
